GET https://localhost:5002/api/categories/ HTTP/1.1
###
GET https://localhost:5002/api/categories/?name=speaker HTTP/1.1 
Accept: application/xml
###
GET https://localhost:5002/api/categories/?name=speaker HTTP/1.1 
Accept: application/json
###
GET https://localhost:5002/api/categories/2 HTTP/1.1 
###
GET https://localhost:5002/api/categories/2 HTTP/1.1
Accept: application/json
###
GET https://localhost:5002/api/categories/abcxy HTTP/1.1
